#include "cct_modules_backward.h"
#include <algorithm>
#include <cmath>
#include <cstdio>

// Values generated by transformer_block_lora_backward_ref.py.

const int TOKENS = 3;
const int EMBED_DIM = 4;
const int MLP_DIM = 6;
const int NUM_HEADS = 2;
const int LORA_RANK = 2;
const float ALPHA = 4.0f;
const int PROBS_SIZE = NUM_HEADS * TOKENS * TOKENS;

float X[12] = {0.125730217f, -0.132104859f, 0.640422642f, 0.104900114f, -0.535669386f, 0.361595064f, 1.304000020f, 0.947080970f, -0.703735232f, -1.265421510f, -0.623274446f, 0.041325979f};
float WQ[16] = {-2.325030804f, -0.218791664f, -1.245911002f, -0.732267380f, -0.544259012f, -0.316300154f, 0.411630541f, 1.042513371f, -0.128534660f, 1.366463423f, -0.665194690f, 0.351510078f, 0.903470159f, 0.094012298f, -0.743499279f, -0.921725392f};
float WK[16] = {-0.457725823f, 0.220195130f, -1.009618163f, -0.209175572f, -0.159225017f, 0.540845573f, 0.214659125f, 0.355372697f, -0.653828621f, -0.129613638f, 0.783975482f, 1.493431091f, -1.259065509f, 1.513923764f, 1.345875382f, 0.781311393f};
float WV[16] = {0.264455616f, -0.313922822f, 1.458020687f, 1.960258365f, 1.801634908f, 1.315103769f, 0.357380420f, -1.208318591f, -0.004454133f, 0.656474948f, -1.288361430f, 0.395122051f, 0.429863691f, 0.696042717f, -1.184117913f, -0.661702573f};
float WO[16] = {-0.436435252f, -1.169801950f, 1.739367843f, -0.495910734f, 0.328969628f, -0.258572549f, 1.583472848f, 1.320361018f, 0.633352637f, -2.203509808f, 0.052028973f, 0.683686197f, 1.003961563f, -0.617907047f, 1.822011352f, -1.320430994f};
float lora_AQ[8] = {-0.661528051f, 0.935050011f, 0.049054615f, 2.002392530f, 0.188519195f, -0.633194089f, -0.377563506f, -1.091146111f};
float lora_BQ[8] = {-1.277680159f, 0.630411506f, 0.581165791f, 1.294558764f, -0.754605770f, 1.689107418f, -0.287387699f, 1.574408293f};
float lora_AV[8] = {-0.432785839f, -0.735483289f, 0.249785379f, 1.031453133f, 0.161009580f, -0.585528851f, -1.341219664f, -1.401520252f};
float lora_BV[8] = {0.502682865f, 0.989713013f, -0.164294586f, -1.074364901f, 0.873042166f, -1.280393958f, -0.713068068f, 0.621017873f};
float W1[24] = {-2.250141144f, 0.386369586f, -0.581640840f, 0.109279700f, -0.075701527f, 0.202114388f, 0.694171965f, -0.758369744f, 1.420982003f, 0.726093769f, 0.843732655f, 1.164863944f, 0.787588239f, 0.844078660f, 0.075593613f, -1.426773906f, -0.135045096f, -0.769514620f, -1.422741771f, 0.258452803f, -0.568549454f, -1.029804468f, -1.043001056f, 0.268417090f};
float W2[24] = {0.358671963f, 1.322457433f, -0.013914669f, 1.041839719f, 1.402264833f, 1.150165677f, -2.365303993f, 1.228683710f, 0.339619994f, 0.423771352f, 0.371227413f, 0.382757157f, 0.319414228f, -0.358913302f, -1.901635289f, -0.108914725f, -0.803731859f, 1.080163360f, -0.288766503f, 0.083475359f, -0.849605978f, -0.510622442f, -0.011533062f, -1.485375166f};
float dOut_seed[12] = {0.300685108f, -0.106072254f, -1.185719848f, -2.398232937f, 0.513052106f, -0.297584027f, -0.530008435f, -0.236154631f, 1.816475987f, -0.049800970f, 0.086619265f, -1.487072825f};
float expected_out[12] = {8.329882622f, -1.889918447f, -1.029574633f, 10.534061432f, 7.564395428f, -1.302848935f, -0.406916857f, 11.345767021f, 7.365556240f, -3.138013363f, -2.042436123f, 10.357536316f};
float expected_dX[12] = {1.354259954f, 14.024385476f, 5.223631823f, -23.991612777f, 1.012879435f, -1.601671872f, -0.030318237f, 0.068415854f, 27.979123337f, -6.832149705f, -15.934088761f, -4.846661500f};
float expected_dAQ[8] = {0.530026376f, 0.408085972f, 0.078230686f, 0.058970746f, -0.392957330f, -0.300842613f, -0.215299606f, -0.166214034f};
float expected_dBQ[8] = {-0.000104285f, 0.000474472f, -0.152495295f, -0.194187999f, 0.000626531f, -0.002850483f, 0.510885298f, 0.650167167f};
float expected_dAV[8] = {4.720323563f, -4.532386303f, 33.827644348f, -29.043060303f, -20.666414261f, 26.560174942f, -17.881549835f, 7.015270233f};
float expected_dBV[8] = {0.036245242f, -5.695713997f, -1.411912799f, -30.203231812f, -0.125207275f, 19.683219910f, -2.132666111f, -45.435089111f};

// Relative tolerance: the reference is numpy float32 with a
// different summation order (and math.erf vs hls::erf), so exact
// equality isn't expected -- only IEEE-754-rounding-level agreement.
bool check(const char *name, const float *got, const float *want, int n, float tol = 5e-3f) {
    bool ok = true;
    for (int i = 0; i < n; i++) {
        float diff = std::fabs(got[i] - want[i]);
        float scale = std::max(1.0f, std::fabs(want[i]));
        if (diff / scale > tol) {
            std::printf("  MISMATCH %s[%d]: got %.9f want %.9f (diff %.9f)\n",
                        name, i, got[i], want[i], diff);
            ok = false;
        }
    }
    std::printf("%s: %s\n", name, ok ? "OK" : "FAIL");
    return ok;
}

int main() {
    float out[TOKENS * EMBED_DIM];
    float layer1_cache[TOKENS * EMBED_DIM];
    float Q_cache[TOKENS * EMBED_DIM];
    float K_cache[TOKENS * EMBED_DIM];
    float V_cache[TOKENS * EMBED_DIM];
    float probs_cache[PROBS_SIZE];
    float layer3_cache[TOKENS * EMBED_DIM];
    float layer4_cache[TOKENS * EMBED_DIM];
    float inner_cache[TOKENS * MLP_DIM];

    transformer_block_lora_forward_train_impl<
        TOKENS, EMBED_DIM, MLP_DIM, NUM_HEADS, LORA_RANK
    >(
        X, WQ, WK, WV, WO,
        lora_AQ, lora_BQ, lora_AV, lora_BV, ALPHA,
        W1, W2,
        out,
        layer1_cache, Q_cache, K_cache, V_cache, probs_cache,
        layer3_cache, layer4_cache, inner_cache
    );

    float dX[TOKENS * EMBED_DIM];
    float dAQ[EMBED_DIM * LORA_RANK];
    float dBQ[LORA_RANK * EMBED_DIM];
    float dAV[EMBED_DIM * LORA_RANK];
    float dBV[LORA_RANK * EMBED_DIM];

    transformer_block_lora_backward_impl<
        TOKENS, EMBED_DIM, MLP_DIM, NUM_HEADS, LORA_RANK
    >(
        X, WQ, WK, WV, WO,
        lora_AQ, lora_BQ, lora_AV, lora_BV, ALPHA,
        W1, W2,
        layer1_cache, Q_cache, K_cache, V_cache, probs_cache,
        layer3_cache, layer4_cache, inner_cache,
        dOut_seed,
        dX, dAQ, dBQ, dAV, dBV
    );

    bool ok = true;
    ok &= check("out", out, expected_out, TOKENS * EMBED_DIM);
    ok &= check("dX", dX, expected_dX, TOKENS * EMBED_DIM);
    ok &= check("dAQ", dAQ, expected_dAQ, EMBED_DIM * LORA_RANK, 2e-2f);
    ok &= check("dBQ", dBQ, expected_dBQ, LORA_RANK * EMBED_DIM, 2e-2f);
    ok &= check("dAV", dAV, expected_dAV, EMBED_DIM * LORA_RANK);
    ok &= check("dBV", dBV, expected_dBV, LORA_RANK * EMBED_DIM);

    std::printf(ok ? "SUCCESS!\n" : "FAIL!\n");
    return ok ? 0 : 1;
}
