#include "cct_modules_backward.h"
#include <algorithm>
#include <cmath>
#include <cstdio>

// Values generated by transformer_block_backward_ref.py.
// Normal (non-LoRA) backprop: WQ/WK/WV/WO/W1/W2 are all trainable
// and all receive real weight gradients.

const int TOKENS = 3;
const int EMBED_DIM = 4;
const int MLP_DIM = 6;
const int NUM_HEADS = 2;
const int PROBS_SIZE = NUM_HEADS * TOKENS * TOKENS;

float X[12] = {0.125730217f, -0.132104859f, 0.640422642f, 0.104900114f, -0.535669386f, 0.361595064f, 1.304000020f, 0.947080970f, -0.703735232f, -1.265421510f, -0.623274446f, 0.041325979f};
float WQ[16] = {-2.325030804f, -0.218791664f, -1.245911002f, -0.732267380f, -0.544259012f, -0.316300154f, 0.411630541f, 1.042513371f, -0.128534660f, 1.366463423f, -0.665194690f, 0.351510078f, 0.903470159f, 0.094012298f, -0.743499279f, -0.921725392f};
float WK[16] = {-0.457725823f, 0.220195130f, -1.009618163f, -0.209175572f, -0.159225017f, 0.540845573f, 0.214659125f, 0.355372697f, -0.653828621f, -0.129613638f, 0.783975482f, 1.493431091f, -1.259065509f, 1.513923764f, 1.345875382f, 0.781311393f};
float WV[16] = {0.264455616f, -0.313922822f, 1.458020687f, 1.960258365f, 1.801634908f, 1.315103769f, 0.357380420f, -1.208318591f, -0.004454133f, 0.656474948f, -1.288361430f, 0.395122051f, 0.429863691f, 0.696042717f, -1.184117913f, -0.661702573f};
float WO[16] = {-0.436435252f, -1.169801950f, 1.739367843f, -0.495910734f, 0.328969628f, -0.258572549f, 1.583472848f, 1.320361018f, 0.633352637f, -2.203509808f, 0.052028973f, 0.683686197f, 1.003961563f, -0.617907047f, 1.822011352f, -1.320430994f};
float W1[24] = {-0.661528051f, 0.935050011f, 0.049054615f, 2.002392530f, 0.188519195f, -0.633194089f, -0.377563506f, -1.091146111f, -1.277680159f, 0.630411506f, 0.581165791f, 1.294558764f, -0.754605770f, 1.689107418f, -0.287387699f, 1.574408293f, -0.432785839f, -0.735483289f, 0.249785379f, 1.031453133f, 0.161009580f, -0.585528851f, -1.341219664f, -1.401520252f};
float W2[24] = {0.502682865f, 0.989713013f, -0.164294586f, -1.074364901f, 0.873042166f, -1.280393958f, -0.713068068f, 0.621017873f, -2.250141144f, 0.386369586f, -0.581640840f, 0.109279700f, -0.075701527f, 0.202114388f, 0.694171965f, -0.758369744f, 1.420982003f, 0.726093769f, 0.843732655f, 1.164863944f, 0.787588239f, 0.844078660f, 0.075593613f, -1.426773906f};
float dOut_seed[12] = {-0.135045096f, -0.769514620f, -1.422741771f, 0.258452803f, -0.568549454f, -1.029804468f, -1.043001056f, 0.268417090f, 0.358671963f, 1.322457433f, -0.013914669f, 1.041839719f};
float expected_out[12] = {6.482642651f, 12.153379440f, 1.157372236f, -5.544095993f, 0.645096779f, 14.509881020f, -1.600669265f, -2.485569000f, 5.260045528f, 10.068738937f, 0.494773746f, -4.637342453f};
float expected_dX[12] = {-27.651062071f, 14.590494951f, 6.071086471f, 4.920630489f, -3.749168096f, 5.510040038f, -1.603077385f, -2.530732234f, -2.198957278f, 4.192935406f, -2.176059893f, 2.891137849f};
float expected_dWQ[16] = {0.236264244f, -0.106854029f, -4.147107601f, -1.334092617f, 0.438285530f, -0.164772376f, -3.679301500f, -0.013801411f, -0.854621053f, 1.033194780f, 7.002267361f, 0.785427094f, 0.180071324f, -0.761568308f, 0.824141085f, 0.562466621f};
float expected_dWK[16] = {2.935194492f, 3.078986883f, 0.389727384f, -0.738397241f, -2.220897675f, -2.454862356f, -0.115318671f, 0.576105833f, -0.701839745f, -1.831612229f, 1.478297949f, 0.328853697f, -0.012456834f, 1.207487464f, -1.752706289f, -0.166562304f};
float expected_dWV[16] = {2.708986282f, 0.525306821f, -2.896739244f, 4.840142250f, 4.619511604f, 1.698551655f, -0.702946603f, 7.245620251f, -3.038776159f, -0.052680802f, 3.396602392f, -8.294422150f, -4.289721012f, -2.171177149f, 0.203082964f, -3.791338205f};
float expected_dWO[16] = {0.844717593f, 0.645001514f, 3.916355352f, -3.064718116f, 0.017420484f, -0.058274550f, 0.159413874f, 0.189208628f, 2.969840113f, 3.118452165f, 8.243237531f, -6.625194704f, 1.375248399f, 2.029128089f, -0.105740411f, -0.022808656f};
float expected_dW1[24] = {1.099100797f, 0.001479012f, 0.134194004f, 0.168304774f, 1.315159301f, 1.913112282f, -2.150894126f, -0.004200107f, -0.310270403f, -1.637782511f, -1.810173324f, -5.155252501f, 0.922367180f, 0.001625963f, 0.126881817f, 0.531662003f, 0.826450005f, 2.030578042f, 0.129426076f, 0.001095133f, 0.049194576f, 0.937815805f, -0.331435875f, 1.211562117f};
float expected_dW2[24] = {-0.198892787f, -0.322672009f, -0.210639134f, 0.032939766f, 0.000108494f, 0.000216511f, 0.000482227f, -0.000218551f, 0.021711478f, 0.034394212f, 0.103050463f, -0.058226142f, -0.034616452f, -0.231672734f, -0.169880122f, -0.103319876f, -0.131991670f, -0.088174939f, -4.413472652f, 3.030553102f, -0.982178450f, -1.245795608f, -9.116220474f, 5.972125530f};

// Relative tolerance: the reference is numpy float32 with a
// different summation order (and math.erf vs hls::erf), so exact
// equality isn't expected -- only IEEE-754-rounding-level agreement.
bool check(const char *name, const float *got, const float *want, int n, float tol = 5e-3f) {
    bool ok = true;
    for (int i = 0; i < n; i++) {
        float diff = std::fabs(got[i] - want[i]);
        float scale = std::max(1.0f, std::fabs(want[i]));
        if (diff / scale > tol) {
            std::printf("  MISMATCH %s[%d]: got %.9f want %.9f (diff %.9f)\n",
                        name, i, got[i], want[i], diff);
            ok = false;
        }
    }
    std::printf("%s: %s\n", name, ok ? "OK" : "FAIL");
    return ok;
}

int main() {
    float out[TOKENS * EMBED_DIM];
    float layer1_cache[TOKENS * EMBED_DIM];
    float Q_cache[TOKENS * EMBED_DIM];
    float K_cache[TOKENS * EMBED_DIM];
    float V_cache[TOKENS * EMBED_DIM];
    float probs_cache[PROBS_SIZE];
    float concatenated_cache[TOKENS * EMBED_DIM];
    float layer3_cache[TOKENS * EMBED_DIM];
    float layer4_cache[TOKENS * EMBED_DIM];
    float inner_cache[TOKENS * MLP_DIM];

    transformer_block_forward_train_impl<
        TOKENS, EMBED_DIM, MLP_DIM, NUM_HEADS
    >(
        X, WQ, WK, WV, WO, W1, W2,
        out,
        layer1_cache, Q_cache, K_cache, V_cache, probs_cache,
        concatenated_cache, layer3_cache, layer4_cache, inner_cache
    );

    float dX[TOKENS * EMBED_DIM];
    float dWQ[EMBED_DIM * EMBED_DIM];
    float dWK[EMBED_DIM * EMBED_DIM];
    float dWV[EMBED_DIM * EMBED_DIM];
    float dWO[EMBED_DIM * EMBED_DIM];
    float dW1[EMBED_DIM * MLP_DIM];
    float dW2[MLP_DIM * EMBED_DIM];

    transformer_block_backward_impl<
        TOKENS, EMBED_DIM, MLP_DIM, NUM_HEADS
    >(
        X, WQ, WK, WV, WO, W1, W2,
        layer1_cache, Q_cache, K_cache, V_cache, probs_cache,
        concatenated_cache, layer3_cache, layer4_cache, inner_cache,
        dOut_seed,
        dX, dWQ, dWK, dWV, dWO, dW1, dW2
    );

    bool ok = true;
    ok &= check("out", out, expected_out, TOKENS * EMBED_DIM);
    ok &= check("dX", dX, expected_dX, TOKENS * EMBED_DIM);
    ok &= check("dWQ", dWQ, expected_dWQ, EMBED_DIM * EMBED_DIM);
    ok &= check("dWK", dWK, expected_dWK, EMBED_DIM * EMBED_DIM);
    ok &= check("dWV", dWV, expected_dWV, EMBED_DIM * EMBED_DIM);
    ok &= check("dWO", dWO, expected_dWO, EMBED_DIM * EMBED_DIM);
    ok &= check("dW1", dW1, expected_dW1, EMBED_DIM * MLP_DIM);
    ok &= check("dW2", dW2, expected_dW2, MLP_DIM * EMBED_DIM);

    std::printf(ok ? "SUCCESS!\n" : "FAIL!\n");
    return ok ? 0 : 1;
}
